#!/usr/bin/env bash
# Vendor a library's public type declarations + docs into a skill's references/
# directory, so an agent can read GROUND-TRUTH source instead of guessing APIs.
#
# Usage:
#   scripts/vendor-library.sh <npm-package>[@version] [dest-name]
#
# Examples:
#   scripts/vendor-library.sh effect
#   scripts/vendor-library.sh @orpc/server@1.14.5
#   scripts/vendor-library.sh zod zod-v4
#
# Run from the skill directory you are authoring (skills/<name>/).
# Writes to ./references/<dest-name>/  (default dest-name derived from the package).
#
# What it captures: *.d.ts / *.d.mts / *.d.cts (the full public API surface),
# markdown docs, and package.json. This is the high-signal, compact subset —
# far more useful to an LLM than a full source tree. If a package ships no types,
# vendor its @types/* package or fall back to a sparse git checkout of src/.
set -euo pipefail

if [ $# -lt 1 ]; then
  echo "usage: $0 <npm-package>[@version] [dest-name]" >&2
  exit 1
fi

SPEC="$1"

# --- parse name + version, handling @scope/name[@version] ---
if [[ "$SPEC" == @* ]]; then
  rest="${SPEC:1}"                      # scope/name[@version]
  if [[ "$rest" == *@* ]]; then
    NAME="@${rest%@*}"; VERSION="${rest##*@}"
  else
    NAME="@$rest"; VERSION=""
  fi
else
  if [[ "$SPEC" == *@* ]]; then
    NAME="${SPEC%@*}"; VERSION="${SPEC##*@}"
  else
    NAME="$SPEC"; VERSION=""
  fi
fi

# --- default dest-name from package: strip @scope marker, / -> __ ---
DEST_NAME="${2:-}"
if [ -z "$DEST_NAME" ]; then
  DEST_NAME="${NAME#@}"; DEST_NAME="${DEST_NAME//\//__}"
fi

PACKSPEC="$NAME"; [ -n "$VERSION" ] && PACKSPEC="$NAME@$VERSION"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Packing $PACKSPEC ..." >&2
if ! npm pack "$PACKSPEC" --pack-destination "$TMP" >/dev/null 2>&1; then
  echo "✗ npm pack failed for $PACKSPEC" >&2
  exit 1
fi

TARBALL="$(ls "$TMP"/*.tgz 2>/dev/null | head -n1)"
[ -z "$TARBALL" ] && { echo "✗ no tarball produced" >&2; exit 1; }
tar -xzf "$TARBALL" -C "$TMP"
SRC="$TMP/package"

ACTUAL_VERSION="$(node -e 'process.stdout.write(require(process.argv[1]).version)' "$SRC/package.json" 2>/dev/null || echo "${VERSION:-unknown}")"

DEST="references/$DEST_NAME"
rm -rf "$DEST"; mkdir -p "$DEST"

# copy type declarations + docs, preserving the package's internal layout
DTS_COUNT=0
( cd "$SRC" && find . \( -name '*.d.ts' -o -name '*.d.mts' -o -name '*.d.cts' -o -iname '*.md' \) -print0 ) \
  | while IFS= read -r -d '' f; do
      mkdir -p "$DEST/$(dirname "$f")"
      cp "$SRC/$f" "$DEST/$f"
    done
cp "$SRC/package.json" "$DEST/package.json" 2>/dev/null || true

DTS_COUNT="$(find "$DEST" -name '*.d.ts' -o -name '*.d.mts' -o -name '*.d.cts' | wc -l | tr -d ' ')"
FILES="$(find "$DEST" -type f | wc -l | tr -d ' ')"
SIZE="$(du -sh "$DEST" | cut -f1)"

cat > "$DEST/VENDORED.md" <<EOF
# Vendored: $NAME

- **Package:** \`$NAME\`
- **Version:** \`$ACTUAL_VERSION\`
- **Source:** \`npm pack $PACKSPEC\`
- **Vendored on:** $(date -u +%Y-%m-%d)
- **Contents:** public type declarations (\`*.d.ts\`), markdown docs, \`package.json\`.

> Ground-truth API surface for agents to read directly. Generated by
> \`create-library-skill\`/\`vendor-library.sh\` — re-run to refresh; do not hand-edit.
EOF

if [ "$DTS_COUNT" -eq 0 ]; then
  echo "⚠ no .d.ts found in $NAME — it may ship no types. Try '@types/${NAME##*/}' or a git sparse checkout of src/." >&2
fi
echo "✓ Vendored $NAME@$ACTUAL_VERSION -> $DEST ($FILES files, $DTS_COUNT type decls, $SIZE)" >&2
echo "  Reference it from SKILL.md so agents know to read it on demand." >&2
